package io.rewynd.common.model

import io.rewynd.model.VideoTrack
import kotlinx.serialization.Serializable

@Serializable
data class ServerVideoTrack(
    val id: String? = null,
    val index: Int,
    val codecName: String? = null,
    val codecLongName: String? = null,
    val profile: String? = null,
    val codecType: String? = null,
    val codecTagString: String? = null,
    val codecTag: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val codedWidth: Int? = null,
    val codedHeight: Int? = null,
    val closedCaptions: Int? = null,
    val filmGrain: Int? = null,
    val hasBFrames: Int? = null,
    val sampleAspectRatio: String? = null,
    val displayAspectRatio: String? = null,
    val pixFmt: String? = null,
    val level: Int? = null,
    val colorRange: String? = null,
    val chromaLocation: String? = null,
    val refs: Int? = null,
    val rFrameRate: String? = null,
    val avgFrameRate: String? = null,
    val timeBase: String? = null,
    val startPts: Int? = null,
    val duration: Double? = null,
    val durationTs: Double? = null,
    val startTime: Double? = null,
    val extradataSize: Long? = null,
    val default: Int? = null,
    val dub: Int? = null,
    val original: Int? = null,
    val comment: Int? = null,
    val lyrics: Int? = null,
    val karaoke: Int? = null,
    val forced: Int? = null,
    val hearingImpaired: Int? = null,
    val visualImpaired: Int? = null,
    val cleanEffects: Int? = null,
    val attachedPic: Int? = null,
    val timedThumbnails: Int? = null,
    val captions: Int? = null,
    val descriptions: Int? = null,
    val metadata: Int? = null,
    val dependent: Int? = null,
    val stillImage: Int? = null,
    val creationTime: String? = null,
    val language: String? = null,
    val encoder: String? = null,
) {
    fun toVideoTrack() =
        VideoTrack(
            index = index,
            name = "$index - $codecName - $language",
            id = id,
            duration = duration,
            codecName = codecName,
            codecLongName = codecLongName,
            profile = profile,
        )
}
