openapi: 3.0.3
info:
  title: Rewynd API Specification
  version: "0.1.0"
  description: Specification for the Rewynd HTTP API
  license:
    name: AGPLv3

paths:
  /api/auth/login:
    $ref: "./resources/auth/login.yaml"
  /api/auth/logout:
    $ref: "./resources/auth/logout.yaml"
  /api/auth/verify:
    $ref: "./resources/auth/verify.yaml"
  /api/user/list:
    $ref: "./resources/user/listUsers.yaml"
  /api/user/create:
    $ref: "./resources/user/createUser.yaml"
  /api/user/delete:
    $ref: "./resources/user/deleteUsers.yaml"
  /api/user/changePassword:
    $ref: "./resources/user/changePassword.yaml"
  /api/user/progress/list:
    $ref: "./resources/progress/listProgress.yaml"
  /api/user/progress/get/{id}:
    $ref: "./resources/progress/getProgress.yaml"
  /api/user/progress/put:
    $ref: "./resources/progress/putProgress.yaml"
  /api/preference/user/put:
    $ref: "./resources/user/preference/putUserPreferences.yaml"
  /api/lib/create:
    $ref: "./resources/library/createLibrary.yaml"
  /api/schedule/create:
    $ref: "./resources/schedule/createSchedule.yaml"
  /api/schedule/delete:
    $ref: "./resources/schedule/deleteSchedule.yaml"
  /api/schedule/get/{id}:
    $ref: "./resources/schedule/getSchedule.yaml"
  /api/schedule/list:
    $ref: "./resources/schedule/listSchedule.yaml"
  /api/lib/delete:
    $ref: "./resources/library/deleteLibrary.yaml"
  /api/lib/scan:
    $ref: "./resources/library/scanLibraries.yaml"
  /api/lib/list:
    $ref: "./resources/library/listLibraries.yaml"
  /api/lib/get/{libraryId}:
    $ref: "./resources/library/getLibrary.yaml"
  /api/movie/list:
    $ref: "./resources/movie/listMovies.yaml"
  /api/movie/get/{movieId}:
    $ref: "./resources/movie/getMovie.yaml"
  /api/show/list:
    $ref: "./resources/show/listShows.yaml"
  /api/show/get/{showId}:
    $ref: "./resources/show/getShow.yaml"
  /api/season/list:
    $ref: "./resources/show/listSeasons.yaml"
  /api/season/get/{seasonId}:
    $ref: "./resources/show/getSeason.yaml"
  /api/episode/list:
    $ref: "./resources/show/listEpisodes.yaml"
  /api/episode/listNext:
    $ref: "./resources/show/listNextEpisodes.yaml"
  /api/episode/listByLastUpdated:
    $ref: "./resources/show/listEpisodesByLastUpdated.yaml"
  /api/episode/get/{episodeId}:
    $ref: "./resources/show/getEpisode.yaml"
  /api/episode/next:
    $ref: "./resources/show/getNextEpisode.yaml"
  /api/search/get:
    $ref: "./resources/search/search.yaml"
  /api/stream/create:
    $ref: "./resources/stream/createStream.yaml"
  /api/stream/delete/{streamId}:
    $ref: "./resources/stream/deleteStream.yaml"
  /api/stream/heartbeat/{streamId}:
    $ref: "./resources/stream/heartbeatStream.yaml"
  /api/stream/{streamId}/index.m3u8:
    $ref: "./resources/stream/getHlsIndexM3u8.yaml"
  /api/stream/{streamId}/stream.m3u8:
    $ref: "./resources/stream/getHlsStreamM3u8.yaml"
  /api/stream/{streamId}/subs.m3u8:
    $ref: "./resources/stream/getHlsSubsM3u8.yaml"
  /api/stream/{streamId}/{segmentId}.vtt:
    $ref: "./resources/stream/getHlsSubs.yaml"
  /api/stream/{streamId}/init-stream.mp4:
    $ref: "./resources/stream/getHlsInitStream.yaml"
  /api/stream/{streamId}/{segmentId}.m4s:
    $ref: "./resources/stream/getHlsSegment.yaml"
  /api/image/{imageId}:
    $ref: "./resources/image/getImage.yaml"

components:
  schemas:
    ImageId:
      $ref: "./schemas/image/ImageId.yaml"
    DeleteLibrariesRequest:
      $ref: "./schemas/library/DeleteLibrariesRequest.yaml"
    Library:
      $ref: "./schemas/library/Library.yaml"
    LibraryId:
      $ref: "./schemas/library/LibraryId.yaml"
    LibraryType:
      $ref: "./schemas/library/LibraryType.yaml"
    ListLibrariesCursor:
      $ref: "./schemas/library/ListLibrariesCursor.yaml"
    ListLibrariesRequest:
      $ref: "./schemas/library/ListLibrariesRequest.yaml"
    ListLibrariesResponse:
      $ref: "./schemas/library/ListLibrariesResponse.yaml"
    ScanLibrariesRequest:
      $ref: "./schemas/library/ScanLibrariesRequest.yaml"
    Actor:
      $ref: "./schemas/media/Actor.yaml"
    AudioTrack:
      $ref: "./schemas/media/AudioTrack.yaml"
    MediaId:
      $ref: "./schemas/media/MediaId.yaml"
    MediaInfo:
      $ref: "./schemas/media/MediaInfo.yaml"
    SubtitleTrack:
      $ref: "./schemas/media/SubtitleTrack.yaml"
    Track:
      $ref: "./schemas/media/Track.yaml"
    VideoTrack:
      $ref: "./schemas/media/VideoTrack.yaml"
    ListMoviesCursor:
      $ref: "./schemas/movie/ListMoviesCursor.yaml"
    ListMoviesRequest:
      $ref: "./schemas/movie/ListMoviesRequest.yaml"
    ListMoviesResponse:
      $ref: "./schemas/movie/ListMoviesResponse.yaml"
    MovieId:
      $ref: "./schemas/movie/MovieId.yaml"
    MovieInfo:
      $ref: "./schemas/movie/MovieInfo.yaml"
    ListProgressCursor:
      $ref: "./schemas/progress/ListProgressCursor.yaml"
    ListProgressRequest:
      $ref: "./schemas/progress/ListProgressRequest.yaml"
    ListProgressResponse:
      $ref: "./schemas/progress/ListProgressResponse.yaml"
    Progress:
      $ref: "./schemas/progress/Progress.yaml"
    ProgressId:
      $ref: "./schemas/progress/ProgressId.yaml"
    CronExpression:
      $ref: "./schemas/schedule/CronExpression.yaml"
    ListSchedulesRequest:
      $ref: "./schemas/schedule/ListSchedulesRequest.yaml"
    ListSchedulesResponse:
      $ref: "./schemas/schedule/ListSchedulesResponse.yaml"
    ScanTask:
      $ref: "./schemas/schedule/ScanTask.yaml"
    Schedule:
      $ref: "./schemas/schedule/Schedule.yaml"
    ScheduleId:
      $ref: "./schemas/schedule/ScheduleId.yaml"
    ScheduleType:
      $ref: "./schemas/schedule/ScheduleType.yaml"
    SearchRequest:
      $ref: "./schemas/search/SearchRequest.yaml"
    SearchResponse:
      $ref: "./schemas/search/SearchResponse.yaml"
    SearchResult:
      $ref: "./schemas/search/SearchResult.yaml"
    SearchResultType:
      $ref: "./schemas/search/SearchResultType.yaml"
    EpisodeId:
      $ref: "./schemas/show/EpisodeId.yaml"
    EpisodeInfo:
      $ref: "./schemas/show/EpisodeInfo.yaml"
    GetNextEpisodeRequest:
      $ref: "./schemas/show/GetNextEpisodeRequest.yaml"
    GetNextEpisodeResponse:
      $ref: "./schemas/show/GetNextEpisodeResponse.yaml"
    ListEpisodesByLastUpdatedCursor:
      $ref: "./schemas/show/ListEpisodesByLastUpdatedCursor.yaml"
    ListEpisodesByLastUpdatedRequest:
      $ref: "./schemas/show/ListEpisodesByLastUpdatedRequest.yaml"
    ListEpisodesByLastUpdatedResponse:
      $ref: "./schemas/show/ListEpisodesByLastUpdatedResponse.yaml"
    ListEpisodesCursor:
      $ref: "./schemas/show/ListEpisodesCursor.yaml"
    ListEpisodesRequest:
      $ref: "./schemas/show/ListEpisodesRequest.yaml"
    ListEpisodesResponse:
      $ref: "./schemas/show/ListEpisodesResponse.yaml"
    ListNextEpisodesCursor:
      $ref: "./schemas/show/ListNextEpisodesCursor.yaml"
    ListNextEpisodesRequest:
      $ref: "./schemas/show/ListNextEpisodesRequest.yaml"
    ListNextEpisodesResponse:
      $ref: "./schemas/show/ListNextEpisodesResponse.yaml"
    ListSeasonsCursor:
      $ref: "./schemas/show/ListSeasonsCursor.yaml"
    ListSeasonsRequest:
      $ref: "./schemas/show/ListSeasonsRequest.yaml"
    ListSeasonsResponse:
      $ref: "./schemas/show/ListSeasonsResponse.yaml"
    ListShowsCursor:
      $ref: "./schemas/show/ListShowsCursor.yaml"
    ListShowsRequest:
      $ref: "./schemas/show/ListShowsRequest.yaml"
    ListShowsResponse:
      $ref: "./schemas/show/ListShowsResponse.yaml"
    SortOrder:
      $ref: "./schemas/util/SortOrder.yaml"
    SeasonId:
      $ref: "./schemas/show/SeasonId.yaml"
    SeasonInfo:
      $ref: "./schemas/show/SeasonInfo.yaml"
    ShowId:
      $ref: "./schemas/show/ShowId.yaml"
    ShowInfo:
      $ref: "./schemas/show/ShowInfo.yaml"
    CreateStreamRequest:
      $ref: "./schemas/stream/CreateStreamRequest.yaml"
    HlsStreamProps:
      $ref: "./schemas/stream/HlsStreamProps.yaml"
    NormalizationMethod:
      $ref: "./schemas/stream/NormalizationMethod.yaml"
    NormalizationProps:
      $ref: "./schemas/stream/NormalizationProps.yaml"
    SegmentId:
      $ref: "./schemas/stream/SegmentId.yaml"
    StreamHeartbeatResponse:
      $ref: "./schemas/stream/StreamHeartbeatResponse.yaml"
    StreamId:
      $ref: "./schemas/stream/StreamId.yaml"
    StreamStatus:
      $ref: "./schemas/stream/StreamStatus.yaml"
    ChangePasswordRequest:
      $ref: "./schemas/user/ChangePasswordRequest.yaml"
    CreateUserRequest:
      $ref: "./schemas/user/CreateUserRequest.yaml"
    DeleteUsersRequest:
      $ref: "./schemas/user/DeleteUsersRequest.yaml"
    ListUsersRequest:
      $ref: "./schemas/user/ListUsersRequest.yaml"
    ListUsersResponse:
      $ref: "./schemas/user/ListUsersResponse.yaml"
    LoginRequest:
      $ref: "./schemas/user/LoginRequest.yaml"
    Password:
      $ref: "./schemas/user/Password.yaml"
    User:
      $ref: "./schemas/user/User.yaml"
    Username:
      $ref: "./schemas/user/Username.yaml"
    UserPermissions:
      $ref: "./schemas/user/UserPermissions.yaml"
    UserPreferences:
      $ref: "./schemas/user/UserPreferences.yaml"
    Timestamp:
      $ref: "./schemas/util/Timestamp.yaml"
